In [1]:
%pip install sklearn

Requirement already satisfied: sklearn in c:\users\abirm\envs\acceptance_venv\lib\site-packages (0.0)
Requirement already satisfied: scikit-learn in c:\users\abirm\envs\acceptance_venv\lib\site-packages (from sklearn) (1.0.2)
Requirement already satisfied: scipy>=1.1.0 in c:\users\abirm\envs\acceptance_venv\lib\site-packages (from scikit-learn->sklearn) (1.8.0)
Requirement already satisfied: numpy>=1.14.6 in c:\users\abirm\envs\acceptance_venv\lib\site-packages (from scikit-learn->sklearn) (1.21.6)
Requirement already satisfied: joblib>=0.11 in c:\users\abirm\envs\acceptance_venv\lib\site-packages (from scikit-learn->sklearn) (1.0.1)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\abirm\envs\acceptance_venv\lib\site-packages (from scikit-learn->sklearn) (3.1.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd
import numpy as np
import sklearn
from sklearn.feature_extraction.text import CountVectorizer, TfidfTransformer
from sklearn.pipeline import Pipeline

In [89]:
refugee = pd.read_csv('1milrefugee_f_dataset.csv', index_col=0)

In [90]:
df = refugee.copy()

In [91]:
df['last_occupation'].value_counts()

Construction Worker                               88977
Mechanic                                          88976
Farmer                                            88899
Fisher                                            88696
Chefs                                             88550
                                                  ...
Senior Administrative Assistant                    1466
Senior Newtwork Engineer                           1457
Senior Machine Learning Professional               1452
Junior Software DeveloperJunior Data Scientist     1441
Senior Software Developer                          1427
Name: last_occupation, Length: 75, dtype: int64

In [92]:
df.head()

,id,language,education_level,last_occupation,predicted_employment_nation,predicted_new_occupation,predicted_new_income,predicted_living_cost,predicted_tax_rate,predicted_tax_ammount,discretionary_income,would_relying_on,predicted_unchr_mandatory_contribution_amount_of_all,accepted_refugee_unhcr_contribution_prediction,single_family_support_contribution,number_of_refugee_family_supported,qualified_for_unhcr_mandatory_contribution,impact_level,mandatory_contribution_range
0,b3e218d26d574d179a9b5a639203a6d8,Native + English + French,High School,Not employed,Canada,Not employed,0,21936,0.00,0.0,-21936.0,unemployemnt benefits,0.0,0.0,248,0.0,not accepted,no impact,£1250 and lower
1,5bcda5b98bdb462d82d122a5bf01dc98,Native + English + French,Primary,Construction Worker,France,Construction Worker,0,16836,0.00,0.0,-16836.0,unemployemnt benefits,0.0,0.0,248,0.0,not accepted,no impact,£1250 and lower
2,928ac2f316bd42e7b429ca325de21d7b,Native,Primary,Farmer,US,Farmer,0,29136,0.00,0.0,-29136.0,unemployemnt benefits,0.0,0.0,248,0.0,not accepted,no impact,£1250 and lower
3,43a0bd7fffe24834855d3fa1b808c3b8,Native + English,Associate Degree,Junior Legal Professional,US,Junior Legal Professional,54275,29136,0.22,11941.0,13198.0,self income,13198.0,13198.0,248,53.0,accepted,medium impact,£8432 to £16864
4,12f75c6c8652411985bbe80f0b3d950c,Native,No Education,Farmer,France,Farmer,0,16836,0.00,0.0,-16836.0,unemployemnt benefits,0.0,0.0,248,0.0,not accepted,no impact,£1250 and lower

In [93]:
df = df.drop(['id', 'predicted_new_occupation', 'predicted_new_income', 'predicted_employment_nation', 'predicted_living_cost', 'predicted_tax_rate', 'predicted_tax_ammount', 'discretionary_income', 'would_relying_on', 'predicted_unchr_mandatory_contribution_amount_of_all', 'accepted_refugee_unhcr_contribution_prediction', 'single_family_support_contribution', 'number_of_refugee_family_supported', 'qualified_for_unhcr_mandatory_contribution', 'impact_level', 'mandatory_contribution_range'], axis=1)

In [94]:
 df=df.loc[[3],['language', 'education_level', 'last_occupation']]

In [95]:
df.head()

           language   education_level            last_occupation
3  Native + English  Associate Degree  Junior Legal Professional

In [96]:
df.to_csv('example_accept_final_dataset.csv')